name: stremio-plugin-czstreams
version: "1.0.0"
slug: stremio_plugin_czstreams
description: CzStreams Stremio addon
startup: services
boot: auto
init: false

arch:
  - amd64
  - aarch64
  - armv7
  - armhf

ports:
  52932/tcp: 52932
ports_description:
  52932/tcp: CzStreams Stremio addon

options:

schema:
  api_key: str
  allowed_hosts:
    - str
  timeout_seconds: int(1,300)
