name: CzStreams
version: "0.1.11"
slug: czstreams
description: Czech and Slovak streams for Stremio
url: https://github.com/lukaskral/stremio-plugin-prehrajto
startup: application
boot: auto
init: false

arch:
  - amd64
  - aarch64

ports:
  52932/tcp: 52932
ports_description:
  52932/tcp: CzStreams Stremio add-on
webui: http://[HOST]:[PORT:52932]/

options: {}

schema: {}
